### ISSUE TITLE
主从节点redis，启动报错，应该怎么配置配置文件？

### ISSUE THREAD

**Issue by Kimi909** [yangwenjie88/delay-queue#3]
org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:135)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:237)
	at org.redisson.Redisson.<init>(Redisson.java:117)
	at org.redisson.Redisson.create(Redisson.java:156)
	at com.yangwenjie.delayqueue.utils.RedissonUtils.<clinit>(RedissonUtils.java:29)
	at com.yangwenjie.delayqueue.core.DelayBucket.getFromBucket(DelayBucket.java:33)
	at com.yangwenjie.delayqueue.core.DelayBucketHandler.run(DelayBucketHandler.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by yangwenjie88** [comment]
Redisson可以看官网文档说明：https://github.com/redisson/redisson/wiki/%E7%9B%AE%E5%BD%95

**Comment by Kimi909** [comment]
ok
